# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e9e5d6505c809cc34504e1e1a4855046c56c1862c033ca3795b6a9573a40afbc544e96bbd00cc39a8c8cedd122c23f228a80bfaa6faa1840215e8a6274162182

test:
  secret_key_base: ef752f5de6ee7e46ac8ba7d6fecdbf6f2c39f4d19c8a841d5efe6f8eda6984ab7a6c7a6075d7c5ade45c637485eba4e221e0c0a2e8dbabd3b3646a7c728f5e96

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
